### ISSUE TITLE
Creating second task does change the date of first task

### ISSUE THREAD

**Issue by telcy** [weDevsOfficial/wp-project-manager#126]
I have created a project with a task list containing one task (with date). When I add a second task and choose a date it does change the date of the first task. It seems to happen since the last update.

**Comment by yeasin1989** [comment]
Hi,

Thank you for finding this issue.

Now we are working on this issue. I will let you know the update after solving this issue. Please allow us the time that we can help you.

Best regards :)

**Comment by yeasin1989** [comment]
Hi,

Thank you for your patience.

We have solved this issue. Now you can get this solved version of the "WP Project Manager" plugin by clicking this link here https://github.com/weDevsOfficial/wp-project-manager/tree/develop.

Cheers :)

**Comment by telcy** [comment]
Thanks for the fix! We are testing it now.

**Comment by telcy** [comment]
works perfect now
