### ISSUE TITLE
When update pro version?

### ISSUE THREAD

**Issue by johnfelipe** [weDevsOfficial/wp-project-manager#132]

**Comment by yeasin1989** [comment]
HI John,

We will release the "WP Project Manager Pro version in the end of this month.
You will get notified on your site about the updates and a notification/news feed to your email.
Please keep patience and allow us some time that we can make our plugin best plugin on the "WordPress" platform.

Thank you for being with us :)

**Comment by johnfelipe** [comment]
@yeasin1989 any advance about pro version?

**Comment by thebengalboy** [comment]
Hello John,

We're done updating the Free version and now working with few advance things of Pro Version.

For the better user experience, We generally release an update after completing 2 step internal testing in our QA department. Hence, we'll release our free version sooner once we get approval from the QA department.

I'm unable to ensure you right now about the Pro version releasing date but as we are almost to the end of the development part, We hope to release it soon as well. 

Regards
