### ISSUE TITLE
Can not use calendar

### ISSUE THREAD

**Issue by stzengpx** [weDevsOfficial/wp-project-manager#169]
I had installed "wedevs-project-manager-pro".
After updating the latest "wedevs-project-manager-v1.6.10.zip", the calendar become all blank.
I tried to turn it back to "wedevs-project-manager-v1.6.9.zip", the calendar is work again.

**Comment by yeasin1989** [comment]
Hi,

Thank you for writing to us.
We have solved this issue and released the "WP Project Manager Pro" plugin version: 1.6.6.
Would you please install and activate the "WP Project Manager version: 1.6.10 and "WP Project Manager Pro" plugin version: 1.6.6. on your site then check your site and let me know the update.

Thank you :)

**Comment by stzengpx** [comment]
Thanks for the update, I can see the calendar now. However, there is no avatar in front of each task item in the new calendar, but there was avatar in the previous version. Would you please let me know how to show the avatar in the new calendar?

**Comment by yeasin1989** [comment]
Hi,

Thank you for writing back to me.
I have checked my local server and our demo site and see everything is working nicely.
Would you please share your valid temporary wp-admin login details while creating a support ticket by clicking this link  https://wedevs.com/account/create-new-ticket/ that I can help you soon.

Thank you :)
