### ISSUE TITLE
Can not read/modify task items

### ISSUE THREAD

**Issue by stzengpx** [weDevsOfficial/wp-project-manager#170]
After upgrade to "wedevs-project-manager-pro-v1.6.6" & "wedevs-project-manager-v1.6.10", the task items can not be read and modified.
Below are two links, the first is clicked from task list -> task item, and the second is clicked from calendar.
Both them always show loading image, but no any content. Once I downgraded to "wedevs-project-manager-pro-v1.6.5" & "wedevs-project-manager-v1.6.9", it works again.
"http://localhost/wp-admin/admin.php?page=cpm_projects&tab=task&action=index&pid=406#/task/438"
"http://localhost/wp-admin/admin.php?page=cpm_projects&tab=task&action=task_single&pid=72#/list/187/task/381"

**Comment by mshossain110** [comment]
Hello,
Thanks for your interest. 
I was trying to reproduce the issue as you described but failed. If it really makes trouble for you, I would suggest you to open a support ticket.

**Comment by stzengpx** [comment]
Thanks, I will re-try it on other environment.
