### ISSUE TITLE
Project Manager Title

### ISSUE THREAD

**Issue by joshnino** [weDevsOfficial/wp-project-manager#173]
Hi! How can I change the title of our project manager from being just plain text "Project Manager" to an image logo we've created it for it?

**Comment by mshossain110** [comment]
Hello,
Thanks for your interest.
The title "Project Manager" is contained in view/project/index.php file. you can copy or edit and add the logo.

**Comment by joshnino** [comment]
Thank you for your response, but how do I get to the page where I can make the edit?

Here’s the URL to our project manager. Just need guidance on how to get there.

http://muycompanies.com/wp-admin/admin.php?page=cpm_projects

Thank you,

JN

**Comment by yeasin1989** [comment]
Hi Joshnino,

Hope you are well.
If you want to change the title of the project then you have to customize the ndex.php file and for that just navigate to wp-content/plugins/project-manager/view/project/index.php file. then you can copy or edit and add the logo.

If you are unable to do that/facing issue then please create a support ticket by clicking this link https://wedevs.com/account/create-new-ticket/ that I can help you.

Best regards :)
