### ISSUE TITLE
Confilct with WP ERP

### ISSUE THREAD

**Issue by advertiseit** [weDevsOfficial/wp-project-manager#192]
When WP Project Manager is activated, WPERP note and schedules are not able to be saved and the time dropdown becomes a non-functioning slider. The “save” buttons are greyed out.

Thanks,
Jason

Uncaught DOMException: Failed to execute ‘registerElement’ on ‘Document’: Registration failed for type ‘trix-toolbar’. A type with that name is already registered.
at Object.t.registerElement (https://***.com/wp-content/plugins/wedevs-project-manager/assets/js/trix.js?ver=4.9.1:15:26023)
at https://***.com/wp-content/plugins/wedevs-project-manager/assets/js/trix.js?ver=4.9.1:16:8245
at https://***.com/wp-content/plugins/wedevs-project-manager/assets/js/trix.js?ver=4.9.1:16:8625
at https://***.com/wp-content/plugins/wedevs-project-manager/assets/js/trix.js?ver=4.9.1:20:23143
at https://***.com/wp-content/plugins/wedevs-project-manager/assets/js/trix.js?ver=4.9.1:20:23261
2jquery-ui-timepicker.js:2109 Error creating Date object from string.
trix.js:20 Uncaught TypeError: Trix.EditorController is not a constructor
at HTMLElement.attachedCallback (trix.js:20)
at V (vue.min.js:6)
at vue.min.js:6
at R (vue.min.js:6)
at D (vue.min.js:6)
at vue.min.js:6
at st (vue.min.js:6)
at Xt.te [as before] (vue.min.js:6)
at pi.insert (vue.min.js:7)
at pi.update (vue.min.js:7)
trix.js:20 Uncaught TypeError: Cannot read property ‘unregisterSelectionManager’ of undefined
at s.Trix.EditorController.s.unregisterSelectionManager (trix.js:20)
at HTMLElement.detachedCallback (trix.js:20)
at z (vue.min.js:6)
at vue.min.js:6
at R (vue.min.js:6)
at P (vue.min.js:6)
at vue.min.js:6
at st (vue.min.js:6)
at ot (vue.min.js:6)
at Xt.ee [as remove] (vue.min.js:6)

**Comment by advertiseit** [comment]
trix.js?ver=4.9.1:15 

Uncaught DOMException: Failed to execute 'registerElement' on 'Document': Registration failed for type 'trix-toolbar'. A type with that name is already registered.
    at Object.t.registerElement (https://dealermark.solutions/wp-content/plugins/wedevs-project-manager/assets/js/trix.js?ver=4.9.1:15:26023)
    at https://dealermark.solutions/wp-content/plugins/wedevs-project-manager/assets/js/trix.js?ver=4.9.1:16:8245
    at https://dealermark.solutions/wp-content/plugins/wedevs-project-manager/assets/js/trix.js?ver=4.9.1:16:8625
    at https://dealermark.solutions/wp-content/plugins/wedevs-project-manager/assets/js/trix.js?ver=4.9.1:20:23143
    at https://dealermark.solutions/wp-content/plugins/wedevs-project-manager/assets/js/trix.js?ver=4.9.1:20:23261
t.registerElement @ trix.js?ver=4.9.1:15
(anonymous) @ trix.js?ver=4.9.1:16
(anonymous) @ trix.js?ver=4.9.1:16
(anonymous) @ trix.js?ver=4.9.1:20
(anonymous) @ trix.js?ver=4.9.1:20
trix.js?ver=20150314:20 Uncaught TypeError: Cannot read property 'unregisterSelectionManager' of undefined
    at s.Trix.EditorController.s.unregisterSelectionManager (trix.js?ver=20150314:20)
    at HTMLElement.detachedCallback (trix.js?ver=20150314:20)
    at z (vue.min.js?ver=20150314:6)
    at vue.min.js?ver=20150314:6
    at R (vue.min.js?ver=20150314:6)
    at P (vue.min.js?ver=20150314:6)
    at vue.min.js?ver=20150314:6
    at st (vue.min.js?ver=20150314:6)
    at ot (vue.min.js?ver=20150314:6)
    at Xt.ee [as remove] (vue.min.js?ver=20150314:6)
Trix.EditorController.s.unregisterSelectionManager @ trix.js?ver=20150314:20
detachedCallback @ trix.js?ver=20150314:20
z @ vue.min.js?ver=20150314:6
(anonymous) @ vue.min.js?ver=20150314:6
R @ vue.min.js?ver=20150314:6
P @ vue.min.js?ver=20150314:6
(anonymous) @ vue.min.js?ver=20150314:6
st @ vue.min.js?ver=20150314:6
ot @ vue.min.js?ver=20150314:6
ee @ vue.min.js?ver=20150314:6
remove @ vue.min.js?ver=20150314:7
update @ vue.min.js?ver=20150314:7
update._update @ vue.min.js?ver=20150314:8
zt.run @ vue.min.js?ver=20150314:7
Vt @ vue.min.js?ver=20150314:6
Wt @ vue.min.js?ver=20150314:6
t @ vue.min.js?ver=20150314:7
characterData (async)
e @ vue.min.js?ver=20150314:7
(anonymous) @ vue.min.js?ver=20150314:7
Bt @ vue.min.js?ver=20150314:6
zt.update @ vue.min.js?ver=20150314:7
_t.notify @ vue.min.js?ver=20150314:7
set @ vue.min.js?ver=20150314:6
set @ vue.min.js?ver=20150314:6
showTab @ crm-app.js?ver=20180104:825
(anonymous) @ vue.min.js?ver=20150314:6
(anonymous) @ VM1969:3
n @ vue.min.js?ver=20150314:8
(anonymous) @ vue.min.js?ver=20150314:6
jquery-ui-timepicker.js?ver=4.9.1:2109 Error creating Date object from string.
trix.js?ver=20150314:20 Uncaught TypeError: Trix.EditorController is not a constructor
    at HTMLElement.attachedCallback (trix.js?ver=20150314:20)
    at V (vue.min.js?ver=20150314:6)
    at vue.min.js?ver=20150314:6
    at R (vue.min.js?ver=20150314:6)
    at D (vue.min.js?ver=20150314:6)
    at vue.min.js?ver=20150314:6
    at st (vue.min.js?ver=20150314:6)
    at Xt.te [as before] (vue.min.js?ver=20150314:6)
    at pi.insert (vue.min.js?ver=20150314:7)
    at pi.update (vue.min.js?ver=20150314:7)
attachedCallback @ trix.js?ver=20150314:20
V @ vue.min.js?ver=20150314:6
(anonymous) @ vue.min.js?ver=20150314:6
R @ vue.min.js?ver=20150314:6
D @ vue.min.js?ver=20150314:6
(anonymous) @ vue.min.js?ver=20150314:6
st @ vue.min.js?ver=20150314:6
te @ vue.min.js?ver=20150314:6
insert @ vue.min.js?ver=20150314:7
update @ vue.min.js?ver=20150314:7
update._update @ vue.min.js?ver=20150314:8
zt.run @ vue.min.js?ver=20150314:7
Vt @ vue.min.js?ver=20150314:6
Wt @ vue.min.js?ver=20150314:6
t @ vue.min.js?ver=20150314:7
characterData (async)
e @ vue.min.js?ver=20150314:7
(anonymous) @ vue.min.js?ver=20150314:7
Bt @ vue.min.js?ver=20150314:6
zt.update @ vue.min.js?ver=20150314:7
_t.notify @ vue.min.js?ver=20150314:7
set @ vue.min.js?ver=20150314:6
set @ vue.min.js?ver=20150314:6
showTab @ crm-app.js?ver=20180104:825
(anonymous) @ vue.min.js?ver=20150314:6
(anonymous) @ VM1969:3
n @ vue.min.js?ver=20150314:8
(anonymous) @ vue.min.js?ver=20150314:6

**Comment by advertiseit** [comment]
If it matters, the server environment is Nginx, CentOS7, PHP 7.1 on WP 4.9.1 and the latest versions of the WeDevs plugins.

**Comment by thebengalboy** [comment]
Hello @advertiseit,

Thanks for noticing the issue. We've fixed this and working to release an update soon.

Thanks for your cooperation :)

**Comment by advertiseit** [comment]
Thanks!
