### ISSUE TITLE
Date/Time Picker Conflict with WP ERP

### ISSUE THREAD

**Issue by advertiseit** [weDevsOfficial/wp-project-manager#194]
Hello, 

With both WP ERP and WP Project Manager activated, the time selector in the Contact/Companies screen reverts to a slider instead of a drop down menu with the times.

This is the error produced: "jquery-ui-timepicker.js:2109 Error creating Date object from string."

When I deactivate CPM, the error goes away and the drop down returns.

Thanks

**Comment by thebengalboy** [comment]
Hello @advertiseit,

Yes, you got it right but that's not a bug indeed! We kept the time selector flexible. Also, the same selector might be implemented with the ERP as well.

Cheers! :)

**Comment by advertiseit** [comment]
Hi @thebengalboy, 

Is there a way force the 12hr dropdown instead of the slider?

Thanks, 
Jason
