### ISSUE TITLE
Group users or "all"

### ISSUE THREAD

**Issue by stianjaco** [weDevsOfficial/wp-project-manager#195]
Is it possible to add a "all" option or "group" when adding a new project. Most of my project uses the same group of 5 people, but it takes to long to add one and one for each project, som I just skip it.

**Comment by advertiseit** [comment]
@stianjaco, Good suggestion. 

+1

**Comment by yeasin1989** [comment]
Hi stianjaco,

You can add all of the group members automatically while creating a project as you can see the video clip here is the link https://drive.google.com/file/d/1ZREHhdlmqRQpARogh0B4-SzMpyCCk6ar/view. Please make sure that you are using the "BuddyPress" plugin, "WP Project Manager Pro" plugin and the "BuddyPress Integration" add-on.

Thank you :)

**Comment by stianjaco** [comment]
Thats all nice if I wanted to use two additional plugins.. But I have otherwise no need for BuddyPress

**Comment by yeasin1989** [comment]
The WP Project Manager Pro plugin and the "BuddyPress Integration" add-on is required the "BuddyPress" plugin (its free) to manage group projects.

**Comment by advertiseit** [comment]
I agree with @stianjaco. This should be a core feature and should not require two additional plugins to simply add teams. No offense, but this is pretty basic functionality for PM software and should work out of the box. I appreciate the buddypress plugin and what it can do for companies that use it, but most organizations don't need half of the features that come with buddypress.

**Comment by yeasin1989** [comment]
@stianjaco @advertiseit 

We always care about our client's needs and work for them.  Hopefully, It will be available in the core plugin in near future.

Thank you  :)
