### ISSUE TITLE
Task List Pagination Not Working

### ISSUE THREAD

**Issue by bscheek** [weDevsOfficial/wp-project-manager#199]
When the task lists and tasks page auto-paginates, two unexpected things happen:

1. The Task List intro page shows for about 15 seconds (as if no task lists exist).
2. The same task lists on page one appear, but now page 2 in the pagination navigation is highlighted.  

Because of this, any task list that has been bumped to page 2 cannot be accessed unless you go to the activity page and select it by link.

Version: 1.6.10 (PRO version) on WP 4.9.2

**Comment by yeasin1989** [comment]
@bscheek ,

I have checked the "WP Project Manager" plugin version: 1.6.10 (free version) on my local server and on our demo site and see everything is working nicely.
Would you please create a support ticket by clicking this link https://wedevs.com/account/create-new-ticket/ that I can help you soon.

Thank you :)

**Comment by yeasin1989** [comment]
@bscheek,

Thank you for your patience.

I have solved the issue and implement fixes on your site. Now everything is working nicely as you can see the video clip here is the link https://drive.google.com/file/d/1q248dPvx3gGX7Kct4XmMrEOO7SJ8B86s/view.
If you have any other questions then please let me know by creating a new ticket that I can help you more.

Best regards :)
