### ISSUE TITLE
Settings / Page Settings needs descriptions

### ISSUE THREAD

**Issue by BrianHenryIE** [weDevsOfficial/wp-project-manager#209]
I don't know what settings at `/wp-admin/admin.php?page=cpm_settings#cpm_page` actually do. It would be useful to put some descriptions/tooltips alongside.

**Comment by yeasin1989** [comment]
@BrianHenryIE 

The settings you have described wp-admin/admin.php?page=cpm_settings is available in Pro version of the plugin. To access projects, my tasks, and my calendar pages on your site frontend you have to set pages in this settings https://prnt.sc/ijdp3l.

Thank you :)
