### ISSUE TITLE
Favicon not showing in chrome on single task view page

### ISSUE THREAD

**Issue by baikaresandeep** [weDevsOfficial/wp-project-manager#228]
Hi Guys,

You are doing a great job by developing this plugin.

I'm using the subtask addon of wp-project-manager, but what I have noticed is that when I'm on the single task page favicon is not going to show up on chrome. It breaks and show as the square icon on production and on localhost it shows xampp icon.

https://www.screencast.com/t/a05bxKkLNle
So did a bit research on this, so what get is there is one template adding in the header here:
https://www.screencast.com/t/4Z0N5bvi

by the hook `cpm_task_single_after`

Hope you get it. Can you please help me why this template added in header??

Regards,
Sandy

**Comment by baikaresandeep** [comment]
I could not see the issue on the firefox. Only on the chrome, I was facing an issue.
Finally, it works for me when I commit the line in `/wp-project-manager/class/task.php`

https://www.screencast.com/t/ILT8SgSDpiXe

And I can't see any referral of this hook in JS or anywhere else as `CPM_task`.

Please let me know.

Thanks.

**Comment by yeasin1989** [comment]
Hi,

Great! Glad that you fixed them.

We have this object for the feature implementation in future.
If you need any technical solution then feel free to create a support ticket here- https://wedevs.com/account/tickets/. We'd love to assist you with the correct guidance.

Best regards.
