### ISSUE TITLE
Due date next and prev button close the datepicker on popup

### ISSUE THREAD

**Issue by baikaresandeep** [weDevsOfficial/wp-project-manager#234]
Hi,

First thing is that the due date next and prev arrow close the datepicker on the popup when I hit the arrow and could not go to next month.
The second thing is I can't remove the due date on the popup.

Regards,
Sandy

**Comment by yeasin1989** [comment]
Hi @baikaresandeep 

It seems like you are using an older version of the WP Project Manager plugin. The plugin is working nicely as you can see the video clip here is the link https://drive.google.com/file/d/1ccySxBw6FCNs8HKTUKNgjHxwT8fpp8VU/view.
Would you please install and activate the latest version: 1.6.16 of the WP Project Manager plugin on your site then check your site and let me know the update.

Thank you :)

**Comment by baikaresandeep** [comment]
Hi @yeasin1989 

Thanks for the response.

Actually, next/prev button of a calendar is not working on the popup(due date).  Also, I have an issue with removing the due date, which I can't remove.
Hope you got it.

Thanks

**Comment by yeasin1989** [comment]
@baikaresandeep,

We do not have such this kind of issue.
It seems like you are using an older version of the plugin or there is a plugin which is conflicting on your site. If you need any technical solution then you can create a support ticket we'd love to help you. Create your ticket here- https://wedevs.com/account/tickets/

Best regards.
