### ISSUE TITLE
Frontend shortcode no department selector

### ISSUE THREAD

**Issue by sammyhampton** [weDevsOfficial/wp-project-manager#240]
When using the frontend short code the "Assign co-worker from departments" is not visible.

Backend View

![backenddept](https://user-images.githubusercontent.com/25824528/44665162-e08b7280-a9da-11e8-8f79-5d231d6a1a44.jpg)

Frontend View
![frontenddept](https://user-images.githubusercontent.com/25824528/44665190-f00abb80-a9da-11e8-9f63-f4de184aac48.jpg)

**Comment by mshossain110** [comment]
This is our pro feature.  we have fixed.
