### ISSUE TITLE
Task due date not showing correctly

### ISSUE THREAD

**Issue by sammyhampton** [weDevsOfficial/wp-project-manager#241]
When selecting a due date in the date picker.

Example  - Selected Aug 28

![datepicker](https://user-images.githubusercontent.com/25824528/44665424-7cb57980-a9db-11e8-86df-04d6069cb5b7.jpg)

Example  - It will show as Aug 28 BUT
![datepicker2](https://user-images.githubusercontent.com/25824528/44665533-c1411500-a9db-11e8-9b11-030591fe07b2.jpg)

Once you hit Update it shows as Aug 27.  

![datepicker3](https://user-images.githubusercontent.com/25824528/44665566-d0c05e00-a9db-11e8-8ad0-e0354d90a98d.jpg)

**Comment by yeasin1989** [comment]
Hi @sammyhampton,

Greetings from the WP Project Manager team.

Already, we have solved this issue as you can see the video clip here https://drive.google.com/file/d/16o2fZW0681uDfmWH1IkmF2eZ70jF25B3/view.

You can install and activate the "WP Project Manager" plugin version: 2.0.5 on your site to get it fixed.

If you face the issue again then you can mail at support@wedevs.com that I can help you as soon as possible.

Thank you :)

**Comment by sammyhampton** [comment]
Yes that is the version Ihave and I still h ave the same issue


![screenshot_3](https://user-images.githubusercontent.com/25824528/44728171-6671f100-aaa1-11e8-8edf-5197a4df3d4f.jpg)

**Comment by yeasin1989** [comment]
@sammyhampton 

You are using an older version of the "WP Project Manager Pro" plugin.
Would you please install the version: 2.0.7 on your site or open a support ticket from your weDevs account to get solved soon.

Thank you :)

**Comment by sammyhampton** [comment]
We have done the update but still have the same issue.

**Comment by sammyhampton** [comment]
And yes I submitted a ticket 2 weeks ago along with a few other issues with some of the paid extensions that are still not working correctly with WP Project and WP ERP .  Still waiting for it to work properly.

**Comment by mshossain110** [comment]
I have checked the issue on my local server. But I was unable to find your problem. You can check the video from here : https://www.useloom.com/share/d155e9c3264f4089aedaff1a1be47af1

If you are still facing this issue on your site. Please create a ticket and I will check your ticket by myself. Please describe the use case when you are facing this issue in the ticket.

We are also solving your issue which you included in your ticket.

Thank you :)

**Comment by alangb01** [comment]
![image](https://user-images.githubusercontent.com/1030736/46836519-6db23d00-cd77-11e8-83e1-dd96e3b4f144.png)


This is what is happening with date with **date format** and **datetime format** for non UTC local timezone

**Comment by agastelo** [comment]
Problem persist in 2.0.13

**Comment by agastelo** [comment]
> ![image](https://user-images.githubusercontent.com/1030736/54235036-62a63900-44de-11e9-8309-b9d220ef1c94.png)
> 
> This is what is happening with date with **date format** and **datetime format** for non UTC local timezone

Problem persist in 2.0.13
