### ISSUE TITLE
Task not showing more than 10 comments

### ISSUE THREAD

**Issue by sammyhampton** [weDevsOfficial/wp-project-manager#243]
When members post more than 10 comments they no longer show up.  No next button to view them and no pagination.  They do post to slack but do not show up on the task.

**Comment by mshossain110** [comment]
Hello, 
Thank you for your information. 

we have solve comment pagination issue.  in new version you will get  update.  if you need urgently you can create out support ticket. 
Thanks

**Comment by yeasin1989** [comment]
Hi tms-islam,

we have solve comment pagination issue in the development version. If you need urgently you can mail directly at support@wedevs.com.

Thank you :)
