### ISSUE TITLE
Project Manager Sub-sub Task

### ISSUE THREAD

**Issue by Ninos** [weDevsOfficial/wp-project-manager#255]
There's a plugin for sub tasks (WP Project Manager Sub Task), but it's not possible to create sub-sub-... tasks for projects.

Also it would be awesome to have the possibility for creating sub-... projects for a project.

So pleace:
1. enhance the addon WP Project Manager Sub Task
2. create a new addon WP Project Manager Sub Project

Would be awesome :-)

**Comment by nayemDevs** [comment]
@Ninos Thanks for your feedback.  Actually, our sub-task module is used to create a sub-task for a parent task only. If you are looking for creating another sub-task underneath a sub-task then it is not possible for now but yes, I kept your suggestion. If we get a similar request in future then we will think about it. You know that a plugin functionality depends on user feedback. 

However, I hope you will keep sharing your amazing idea with us.

**Comment by Ninos** [comment]
Is it hard to implement? If not, how could I change enhance that feature?
