### ISSUE TITLE
Error states requires PHP 5.6 or higher but i'm using 5.6

### ISSUE THREAD

**Issue by hyperioware** [weDevsOfficial/wp-project-manager#277]
I've been getting an error stating that the plugin requires PHP 5.6 or higher to run, I just switched to 5.6 and it still gives me this error.

**Comment by nayemDevs** [comment]
Hello,

If you are using PHP version 5.6 or later and still getting an issue then kindly create a support ticket from your weDevs account or send direct e-mail to support@wedevs.com so that our team can check your website and solve the problem for you :)
