### ISSUE TITLE
Estimates of Todos, Timelog, and Reporting feature

### ISSUE THREAD

**Issue by wqr786** [weDevsOfficial/wp-project-manager#29]
Great plugin.

I think we need to have Estimates on Todos, and based on those Estimates, we need to have Time Log functionality, where Users can punch their time against the Todos, and then basic Reports such as a Todo List shows how much time estimated for all todos, and how much time is spent in actual till now.

Then Advanced Reporting would be good too, where Management can see the total Project's Estimate, and Total Time spent. I think it would be good to have something like a Burndown chart where we can see the graph starting from a point and ending at an estimated point, and the other line in the graph showing the actual point. This task I think is a quite major feature (in terms of efforts required). Anyone to vote for it? I might actually work on it if it can be funded by someone.

**Comment by ELyukio** [comment]
It will be great
