### ISSUE TITLE
Calendar bug with Persian Language

### ISSUE THREAD

**Issue by Samiiix** [weDevsOfficial/wp-project-manager#291]
Hello there.
The Calendar doesn't show tasks when site language is set to Persian.

**Comment by yeasin1989** [comment]
Hi @Samiiix,

Thanks for writing here.

Already, we have solved this issue and it will appear in the next release. If you want this feature now then send a direct email by using this [form](https://wedevs.com/account/create-new-ticket/). Our team will review and solve your problem.

Also, The WP Project Manager is not 100% RTL language compatible for now but we are working on it to make properly RTL compatible for the future releases.

Cheers!
