### ISSUE TITLE
Kanban issue - new tasks not showing

### ISSUE THREAD

**Issue by kevjustice** [weDevsOfficial/wp-project-manager#304]
We are just testing this module to see if it will work for us.  I noticed when I add a task in task view and then switch to kanban view (even if you do a refresh first) that the new task does not show up.  In the "OPEN" column I click add and type the same name for the task, it searches and shows up in the drop down but clicking it gives me this error: 

This task already included in others column.

However there is no "others" column, only "Open", "In Progress", "Done", "Overdue".  I created an "Others" column but that did show any of the missing tasks or stop the error from showing.

**Comment by yeasin1989** [comment]
Hi @kevjustice 

I hope you are doing well :)

When you add a task in the task view it will not show on Kanban Board by default and you have to add an existing task into the Kanban Board as you can see the video clip here https://www.loom.com/share/c34db97e93bd4f59bd9f22d075d67f42.

However, I have checked and see everything is working fine on our site. I need to check your site. In that case, you have to send a direct email by using this [form](https://wedevs.com/account/create-new-ticket/). Our team will review and solve your problem.

Best regards.
