### ISSUE TITLE
Add ''Create New Task'' at primary menu in WP Project Manager

### ISSUE THREAD

**Issue by ixehad** [weDevsOfficial/wp-project-manager#306]
It is difficult to find ''Add Task'' from the project as many steps need to go for adding a new task.

**Comment by yeasin1989** [comment]
Hi @ixehad,

Thanks for the comment.

We have built the WP Project Manager plugin by following the default WordPress method, where the projects are loads in WordPress and the task, comment, discussion, milestone etc. loads in projects. So, if we want to add a task then you have to create a project and task list first. Also, our existing users of the plugin are not facing any difficulties to add a task by following the default instruction.

For any further query, and get help soon you can contact [here](https://wedevs.com/contact).

Thanks for your understanding :)

**Comment by ediamin** [comment]
@asaquzzaman if you can, please make this happen as soon as you can.
