### ISSUE TITLE
Need keyboard shortcut to create projects and tasks

### ISSUE THREAD

**Issue by ixehad** [weDevsOfficial/wp-project-manager#314]
Users should easily create tasks and projects. If there are keyboard shortcodes to create projects or tasks from any dashboard, it will save time and reduce the process.

**Comment by yeasin1989** [comment]
Hi @ixehad 

Thanks for your suggestion.

Already, we have implemented the "create task" keyboard shortcut and you will get it in the next version release.

Also, I have kept your suggestion in our log. I hope you will get a "create a project" keyboard shortcut in future releases.

If you have any further questions/suggestions then you can send a direct email by using this [form](https://wedevs.com/account/create-new-ticket/). 

Best regards.

**Comment by Rubaiyat-E-Mohammad** [comment]
> Hi [@ixehad](https://github.com/ixehad)
> 
> Thanks for your suggestion.
> 
> Already, we have implemented the "create task" keyboard shortcut and you will get it in the next version release.
> 
> Also, I have kept your suggestion in our log. I hope you will get a "create a project" keyboard shortcut in future releases.
> 
> If you have any further questions/suggestions then you can send a direct email by using this [form](https://wedevs.com/account/create-new-ticket/).
> 
> Best regards.

Already implemented
