### ISSUE TITLE
Cannot load categories, projects etc.

### ISSUE THREAD

**Issue by SirVectrex** [weDevsOfficial/wp-project-manager#322]
Using newest Wordpress version and newest Project Manager. Cannot access any of the Project Managers assets. No error message. Infinite loading.

![image](https://user-images.githubusercontent.com/43294797/68990541-baa6f380-0854-11ea-8486-0fd15fc5d11b.png)

**Comment by yeasin1989** [comment]
Hi @SirVectrex,

Please do not worry, Yeasin is here to help you.

It seems like the site URL or permalink is not set correctly and creating the problem. However, would you please check a few points mentioned below?

01. Is WP JSON enabled at your WordPress site?
02. Is your permalink set up for a pretty URL?
03. Is there any third party javascript library conflict?

If the above points are working fine then we need to check your site. In that case, you have to send a direct email by using this [form](https://wedevs.com/account/create-new-ticket/). Our team will review and solve your problem.

Best regards.

**Comment by SirVectrex** [comment]
Hi @yeasin1989 ,

Thanks for reaching out! A JavaScript library conflict seems to have been the issue! 
Working fine now!

Thanks a lot, 
Cheers!
