### ISSUE TITLE
The client label is not aligned with the client settings column in the project settings.

### ISSUE THREAD

**Issue by yeasin1989** [weDevsOfficial/wp-project-manager#326]
Hi @asaquzzaman,

The client label is not aligned with the client settings column in the project settings.

To reproduce the issue just navigate to the wp-admin>project manager>projects>click on a project>settings you will see the client settings column aligned left which is not good to display as you can  see the screenshot https://prnt.sc/q6xr9s so we can align right it will be nice as you can see the screenshot https://prnt.sc/q6xpg7

Please fix it and release a new version.

Thank you :)

**Comment by asaquzzaman** [comment]
https://bitbucket.org/wedevs/cpm-pro-module/commits/af9acf5b5f599a1726cc0915f2088a6919d6fbc7
