### ISSUE TITLE
Fatal error after reinstallation.

### ISSUE THREAD

**Issue by AdamQuadmon** [weDevsOfficial/wp-project-manager#327]
After a failed import of 30 trello boars I removed the plugin to try again.

Now installing it again it's showing a Fatal error:

Fatal error: Class WeDevs\PM\Core\DB_Connection\Model contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Queue\QueueableEntity::getQueueableRelations, Illuminate\Contracts\Queue\QueueableEntity::getQueueableConnection, Illuminate\Contracts\Routing\UrlRoutable::resolveRouteBinding) in /srv/www/test/current/web/app/plugins/wedevs-project-manager/core/DB_Connection/Model.php on line 11

Do you have any suggestions?

**Comment by yeasin1989** [comment]
Hi @AdamQuadmon,

Please do not worry, It can be fixed.

We need to check your site. In that case, you have to send a direct email by using this [form](https://wedevs.com/contact). Our team will review and solve your problem.

Best regards.

**Comment by AdamQuadmon** [comment]
Hi @yeasin1989,
thanks for your work and your quick reply.
My website is fortunately on local development, so is not possible to give you the link and the admin password, and if it was in production I really doubt that giving admin access could have be a viable thing.

Anyway I submitted the same ticket over there

Thanks again

**Comment by yeasin1989** [comment]
Hi @AdamQuadmon,

Thanks for the update.

I have checked on my local server and see everything is working fine.
Please try to install and activate the WP Project Manager plugin on a new WordPress installation. I hope it will work for you.

Also, I have replied to your ticket, please continue with that to get updates.

Thanks again.

**Comment by AdamQuadmon** [comment]
Unfortunately a new Wordpress install is not a solution neither giving you root access to my project.
Plus, finding a solution here can be useful for other users in the same situation.

Is there any composer or wordpress cache,  wp-option or table in the database, that can affect a reinstallation?

If you say "try a new wordpress installation" you know your plugin leave stuff on the project after uninstall it, can you please help me spot what?

Could be a PHP 7.3 incompatibility? Which version of lavarel are you using that ?

Hope you can give me some hints to investigate the issue as this look like a promising project

**Comment by yeasin1989** [comment]
Hi @AdamQuadmon ,

It seems like there is a third party plugin that is conflicting on your site and I am unable to say anything without checking your site.

Now please deactivate all of your activated plugins then activate the WP Project Manager plugin I hope it will work, then you can find out the conflict plugins by activating them one by one.

Thanks for your understanding.
