### ISSUE TITLE
Task duplicate from task lists

### ISSUE THREAD

**Issue by FaraziF** [weDevsOfficial/wp-project-manager#333]
**Given** As an admin

**When** Mouse hover in an individual task

And Click pm more option

And Click the duplicate link

**Then** Subtasks are not duplicating

And Custome fields data not duplicating

**Comment by asaquzzaman** [comment]
https://bitbucket.org/wedevs/cpm-pro-module/commits/c1944fdf18b18191649ee51c0d635cf802ea96c2
