### ISSUE TITLE
error on subsite of multisite

### ISSUE THREAD

**Issue by masterseoonline** [weDevsOfficial/wp-project-manager#337]
when enabled this plugin on my subsite of multisite, this error appear....

`
Fatal error: Uncaught Exception: Table 'ndb.wp_52_users' doesn't exist in www\wpmulara\wp-content\plugins\wedevs-project-manager2\vendor\tareq1988\wp-eloquent\src\Eloquent\Database.php:150 Stack trace: #0 www\wpmulara\wp-content\plugins\wedevs-project-manager2\vendor\illuminate\database\Query\Builder.php(1705): WeDevs\ORM\Eloquent\Database->select('select * from `...', Array, true) #1 www\wpmulara\wp-content\plugins\wedevs-project-manager2\vendor\illuminate\database\Query\Builder.php(1690): Illuminate\Database\Query\Builder->runSelect() #2 www\wpmulara\wp-content\plugins\wedevs-project-manager2\vendor\illuminate\database\Eloquent\Builder.php(462): Illuminate\Database\Query\Builder->get(Array) #3 www\wpmulara\wp-content\plugins\wedevs-project-manager2\vendor\illuminate\database\Eloquent\Builder.php(446): Illuminate\Database\Eloquent\Builder->getModels(Array) #4 www\wpmulara\wp-content\plugins\wedevs-project-manager2\vendor\illumin in www\wpmulara\wp-content\plugins\wedevs-project-manager2\vendor\tareq1988\wp-eloquent\src\Eloquent\Database.php on line 150`

when I create dummy table on subsite "wp_52_users", error message disapear....
*tested Version 2.3.5 working well, problem only on Version 2.3.6

**Comment by mshossain110** [comment]
@asaquzzaman 
this issue will be solved if you uncomment this function 

https://github.com/weDevsOfficial/wp-project-manager/blob/develop/src/User/Models/User.php#L29

**Comment by masterseoonline** [comment]
> 
> 
> @asaquzzaman
> this issue will be solved if you uncomment this function
> 
> https://github.com/weDevsOfficial/wp-project-manager/blob/develop/src/User/Models/User.php#L29

tested, and solved by this solution....thx
