### ISSUE TITLE
Ошибки в мобильном отображении

### ISSUE THREAD

**Issue by wen89** [weDevsOfficial/wp-project-manager#339]
Добрый день. Долго ожидал что с обновлениями поправите работу с вашим плагином через телефон. Однако этого не происходит. Многие элементы не адаптированы под телефон и вызывают ошибки в отображении интерфейса.

Если я могу вам помочь, я готов поделиться с вами своими правками в CSS, которые уже сделал у себя на сайте. Что скажите на это?

**Comment by asaquzzaman** [comment]
@wen89 
Thanks for you contribution. Please send us a pull request we will merge your code after review it.

**Comment by yeasin1989** [comment]
Здравствуй @wen89,

Спасибо за ваш вклад.
Было бы очень полезно, если вы отправите запрос на удаление, мы объединим ваш код после его просмотра.

С наилучшими пожеланиями.
