### ISSUE TITLE
Fatal Error when activating

### ISSUE THREAD

**Issue by derekm139** [weDevsOfficial/wp-project-manager#340]
Fatal error: Uncaught Error: Call to undefined function Illuminate\Support\mb_strpos() in /var/www/timemode/wp-content/plugins/wedevs-project-manager/vendor/illuminate/support/Str.php:94 Stack trace: #0 /var/www/timemode/wp-content/plugins/wedevs-project-manager/vendor/illuminate/database/Query/Builder.php(535): Illuminate\Support\Str::contains('key', '->') #1 /var/www/timemode/wp-content/plugins/wedevs-project-manager/vendor/illuminate/database/Eloquent/Builder.php(211): Illuminate\Database\Query\Builder->where('key', '=') #2 /var/www/timemode/wp-content/plugins/wedevs-project-manager/vendor/illuminate/database/Eloquent/Model.php(1374): Illuminate\Database\Eloquent\Builder->where('key', 'managing_capabi...') #3 /var/www/timemode/wp-content/plugins/wedevs-project-manager/vendor/illuminate/database/Eloquent/Model.php(1386): Illuminate\Database\Eloquent\Model->__call('where', Array) #4 /var/www/timemode/wp-content/plugins/wedevs-project-manager/db/seeds/RoleTableSeeder.php(44): Illuminate\Database\Eloquent\Model::__callStat in /var/www/timemode/wp-content/plugins/wedevs-project-manager/vendor/illuminate/support/Str.php on line 94

**Comment by helloworldwhoami** [comment]
@derekm139 

This is not our plugin issue. Its about your PHP configuration. Please contact with your hosting provider to active **mb_strpos()** this function. Or you can do it your self. Please check the following link https://stackoverflow.com/questions/9692157/php-missing-mb-strpos-function

**Comment by asaquzzaman** [comment]
@derekm139

This is not our plugin issue. Its about your PHP configuration. Please contact with your hosting provider to active mb_strpos() this function. Or you can do it your self. Please check the following link https://stackoverflow.com/questions/9692157/php-missing-mb-strpos-function
