### ISSUE TITLE
HTML tags in slack notification.

### ISSUE THREAD

**Issue by yeasin1989** [weDevsOfficial/wp-project-manager#341]
After configuring the WP Project Manager slack integration it's showing notifications on slack with the HTML tags as you can see the screenshot https://prntscr.com/rlnm95.

Please fix this issue as soon as possible.

**Comment by asaquzzaman** [comment]
https://bitbucket.org/wedevs/cpm-pro-module/commits/0ba87946dfd37f21a193619850369503c561203f
