### ISSUE TITLE
Use word-break: break-word, instead of break-all

### ISSUE THREAD

**Issue by ediamin** [weDevsOfficial/wp-project-manager#343]
Current style
```
#wedevs-project-manager #pm-single-task-wrap .pm-task-comment-wrap .pm-comment-content {
    // ...
    word-break: break-all; 
}
```

This should change to `break-word`. break-all breaks chars of a single word and show them in two lines, which should be avoid.

**Comment by asaquzzaman** [comment]
https://docs.google.com/document/d/1ZVKyWRv-cmGPrYSMHjyIm8RIvGtVepbTzRR6Z0hGGY/edit

break-all is appropriate when user using this kind of link.

**Comment by ediamin** [comment]
@asaquzzaman break-word can solve that problem too. Take a look at this example https://codepen.io/ediamin/pen/QWjGBBL

**Comment by asaquzzaman** [comment]
@ediamin Fixed the issue https://github.com/weDevsOfficial/wp-project-manager/commit/ce1d93c6ecef2abc546016eb75333a9a695138bf
