### ISSUE TITLE
Edit project from project dasboard

### ISSUE THREAD

**Issue by FaraziF** [weDevsOfficial/wp-project-manager#345]
As an admin
Click project manager and all projects are showing
Click an edit option from individual project
Only delete option is showing but other option not showing

**Reference:** https://prnt.sc/rzr3gi

**Comment by asaquzzaman** [comment]
https://github.com/weDevsOfficial/wp-project-manager/commit/926df32a025d72bb20dfa7e978691942a3ce1a8c
