### ISSUE TITLE
Duplicate Project issue

### ISSUE THREAD

**Issue by pratikgandhi1411** [weDevsOfficial/wp-project-manager#348]
If I DUPLICATE an existing PROJECT which has files attached to it… the DUPLICATE COPY of the project will NOT retain the files from the original project.

Thanks

**Comment by asaquzzaman** [comment]
@pratikgandhi1411 

Fixed this issue but its a pro feature so you have to wait for upcoming release.  

https://bitbucket.org/wedevs/cpm-pro-module/commits/8bd6a5124f0954e15000002f2556fe7e148f805e
