### ISSUE TITLE
Add a search tasks option in My Task page

### ISSUE THREAD

**Issue by ediamin** [weDevsOfficial/wp-project-manager#353]
We should have a search tasks option in My Task page just like in projects pages.

**Comment by asaquzzaman** [comment]
We have already search option in my-tasks page. Right now we have no plan to add extra search option in same page. You can suggest how to improve the existence search option in my-tasks page.

**Comment by ediamin** [comment]
Oops sorry my bad. I was looking for the search bar in top left corner. 👍
