### ISSUE TITLE
General calendar acting like my calendar.

### ISSUE THREAD

**Issue by yeasin1989** [weDevsOfficial/wp-project-manager#354]
The general calendar showing tasks/milestones assigned to the logged-in user not all of the users.
I have created a video clip as you can see here https://drive.google.com/file/d/14Bq3DGMutjaoQhADNOn7Ay0i4C5lklwl/view

I hope it will be fixed soon.

Thank you :)

**Comment by asaquzzaman** [comment]
https://bitbucket.org/wedevs/cpm-pro-module/commits/37156b948d09d95443e82eadc585ab3d706811e0
