### ISSUE TITLE
User image & Calendar icon is visible when select task lists

### ISSUE THREAD

**Issue by FaraziF** [weDevsOfficial/wp-project-manager#359]
**Given** as an admin
**When** Preview my task and click Add new task button
And Select a task list
**Then** User image & Calendar icon is showing from add new task field

Reference: https://prnt.sc/spa0ba

**Comment by asaquzzaman** [comment]
https://github.com/weDevsOfficial/wp-project-manager/commit/6b58840a539993f00147583b0570c724ae5f2e21
