### ISSUE TITLE
WP Rest API Request killing pages(die()) on its own for some endpoints

### ISSUE THREAD

**Issue by josephbada-monster** [weDevsOfficial/wp-project-manager#364]
Hello weDevs!
I would like to submit an issue here using your REST API endpoints
here is a video: https://www.loom.com/share/b2d6fa95b7f0422f83c9039a58401344

We have in our test envionment your WP Project Manager v 2.3.10
and im trying to communicate using the REST requests.

When i try using your pm/v2/projects (and some other endpoints) its issuing its own die() command after printing out the page, ignoring other commands that followed

Can you please enlighten me if this is not really an issue and im doing something wrong?

Regards
Joseph

**Comment by josephbada-monster** [comment]
https://www.loom.com/share/7487168285784ed7a1f52d1c008a18e9
I think i found the root of the issue please check this video

**Comment by josephbada-monster** [comment]
Following up. can anyone please check this?

**Comment by asaquzzaman** [comment]
@josephbada-monster 
Sorry for getting late, we are busy with others issue. 

We do not find this kind of issue in our development environment and there is no video exist with this link https://www.loom.com/share/b2d6fa95b7f0422f83c9039a58401344

Can you reproduce the video again?
