### ISSUE TITLE
Category filtering bug

### ISSUE THREAD

**Issue by tareq1988** [weDevsOfficial/wp-project-manager#365]
**Project Category** should be renamed to **All Categories**

Selecting the **All Categories**  should show all the projects, right now it's showing zero results.

![2020-06-16 at 12 26 PM](https://user-images.githubusercontent.com/153669/84731934-f5306480-afcc-11ea-84bc-c1c998403e3f.gif)

**Comment by asaquzzaman** [comment]
https://github.com/weDevsOfficial/wp-project-manager/commit/f5cddd63544c84055ff618125c289b5368b8ebd5
