### ISSUE TITLE
Could not delete/remove the description of a task list.

### ISSUE THREAD

**Issue by yeasin1989** [weDevsOfficial/wp-project-manager#368]
Hi,

This is not possible to remove/delete the description from the task list as you can see the video clip here https://drive.google.com/file/d/1KhUrXRbyz7wE_UicZxaKDHNLiDtjbp_J/view?usp=drivesdk

To reproduce the issue just create a task list with description now try to remove/delete the description by editing the task list.
I have checked on the local server and live site with the latest version of the plugin.

Thank you :)

**Comment by asaquzzaman** [comment]
@yeasin1989 

Fixed https://github.com/weDevsOfficial/wp-project-manager/commit/7bff0ee0c88907c8f8ec5acc25acf86243671931
