### ISSUE TITLE
Estimation time in sub-task.

### ISSUE THREAD

**Issue by yeasin1989** [weDevsOfficial/wp-project-manager#370]
Hi,

We can set estimation time on a subtask but there is no way for the co-worker to know they have an estimation on their assigned sub-task.

To reproduce the issue, just create a sub-task with an estimation time and assign a co-worker. Now login with that co-worker credentials and check the sub-task boom there is no estimation time showing Also, there is no column for the estimation time in reports.

Thank you :)

**Comment by asaquzzaman** [comment]
@yeasin1989 
Done! check in next release.
