### ISSUE TITLE
Issues from the report.

### ISSUE THREAD

**Issue by yeasin1989** [weDevsOfficial/wp-project-manager#371]
Hi,

User activity reports always showing **No Data Found, Please search again!** even if we filter by date/project/user as you can see the screenshot https://prnt.sc/tbuzql and https://prnt.sc/tbuzdi.

To reproduce the issue just navigate to the project manager>reports>user activities>click on view report boom no data also try to filter boom no data.

NB: try to get user activity reports except for admin

Thank you :)

**Comment by asaquzzaman** [comment]
@yeasin1989 

Fixed the issue you will get it in next release.
