### ISSUE TITLE
Error download file 

### ISSUE THREAD

**Issue by tungduongtruong** [weDevsOfficial/wp-project-manager#373]
Hello, 

I using WP Project Manager version 2.3.11 and error message when i click download file:

{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}

Why 2 // in URL

**https://domain.xyz/wp-json//pm/v2/projects/18/files/4702/users/1/download**

![image](https://user-images.githubusercontent.com/63650317/87271459-824bd800-c4fd-11ea-8504-15a0c36b9f97.png)

**Comment by yeasin1989** [comment]
Hi @tungduongtruong,

Thanks for writing here.
Already, we have fixed this issue and will release a new version within the next week.

To get an immediate fix just contact us directly through our [website](https://wedevs.com/contact) that we can check your site and implement fixes soon.

Best regards.
