### ISSUE TITLE
Milestone is not showing on the General Calendar

### ISSUE THREAD

**Issue by yeasin1989** [weDevsOfficial/wp-project-manager#382]
Hi,

I have checked with the latest version of the plugins.
You can create a milestone in a project then navigate to the general calendar you will see there is no milestone showing on the date.

Please check and fix it soon.

Thank you.

**Comment by asaquzzaman** [comment]
Do you check it properly. I have checked and its working fine. May be you forget assign the milestone due date at milestone create time. Without milestone due date it will not appear in calendar.
