### ISSUE TITLE
After hitting archive list hive does not show on archive  

### ISSUE THREAD

**Issue by makdhk** [weDevsOfficial/wp-project-manager#387]
In a project when user archive any "Task list" it disappear form the list but when user go to archive it does not show in archive list. https://prnt.sc/ukhdw9

**Comment by yeasin1989** [comment]
Hi,

Thanks for writing here.

I have checked and found this issue.
Our plugin developer will fix this issue and release a new version. Please keep patience and allow us the time that we can help you.

Best regards.
