### ISSUE TITLE
every member see every project

### ISSUE THREAD

**Issue by heidongqilin** [weDevsOfficial/wp-project-manager#400]
every member see every project
What's going on?

**Comment by thebengalboy** [comment]
Hello @heidongqilin 

Sorry for the inconvenience. Seems all of your users have project managing capabilities. You can prevent that by simply editing/updating the specific user profile.

[This documentation](https://wedevs.com/docs/wp-project-manager/settings/new-user-role-capability/) might help you to manage the user basis project capabilities.

Thanks
