### ISSUE TITLE
WP Project Manager free and pro plugins are not 100% translating.

### ISSUE THREAD

**Issue by yeasin1989** [weDevsOfficial/wp-project-manager#407]
Hi,

I tried to translate the Project Manager free and pro into the Italian language, but not all words have been translated. Buttons "Create folder, Upload to file etc" have not been translated. 
Also, here is the screenshot list of the non translated strings https://prntscr.com/wmepfq https://prntscr.com/wmeptr https://prntscr.com/wmeqvt https://prntscr.com/wmer4p https://prntscr.com/wmermr

Please check and fix it.

Thank you :)

**Comment by asaquzzaman** [comment]
https://github.com/weDevsOfficial/wp-project-manager/commit/b428e8d5b194e309ce671febd3782ad8d81bc866
