### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by HoratioShaw** [weDevsOfficial/wp-project-manager#420]
When I enable the plug-in in Wordpress 5.8, a fatal error will appear.

**Comment by yeasin1989** [comment]
Hi @HoratioShaw,

Thanks for creating an issue.

We have checked the compatibility between WordPress 5.8 and WP Project Manager 2.4.13.
There is no such issue we have found.

It seems like there is a technical issue on your site.
No worries, just contact our support [here](https://wedevs.com/contact) our technical support team will look up on your site why this is happening.

Best regards.

**Comment by Rubaiyat-E-Mohammad** [comment]
Not an issue
