### ISSUE TITLE
Could not download the attached file from the my tasks section.

### ISSUE THREAD

**Issue by yeasin1989** [weDevsOfficial/wp-project-manager#422]
We are having an issue with downloading file attachments that are attached to comments on tasks. When a user goes to the “My Tasks” area and opens a task, they cannot download files. 

Steps to reproduce:

– Create a project and task.
– Assign the task to another user.
– Add a comment to the discussion area of the task and attach a file.
– Login as the other user and go to Project Manager –> My Tasks.
– Click on the task name to open the task.
– Click on the file attachment.

Please check and fix the issue.

Thank you.

**Comment by ManiruzzamanAkash** [comment]
It's fixed on #424
