### ISSUE TITLE
any one can delete/complete the project?

### ISSUE THREAD

**Issue by gangdai** [weDevsOfficial/wp-project-manager#61]
looks like anyone can delete/complete a project even they do not have permission. pls let me know if there are quick fix / work around

**Comment by gangdai** [comment]
wordpress 4.4.2. and wp-project-manager1.4.1

**Comment by tareq1988** [comment]
Did you checked the settings area? Project Manager -> Settings and in the General Tab, check the project create and manage capability.

**Comment by gangdai** [comment]
Thanks I did one subscriber (which is neither Project Manage Capability or Project Create Capability) and not related to the project can delete and complete the project by clicking the little gear icon
